### ISSUE TITLE
RuntimeError: Verification of custom image failed: Unable to instantiate workflow template.

### ISSUE THREAD

**Issue by farahfa** [GoogleCloudDataproc/cloud-dataproc#133]
Hello,

I'm trying to build custom dataproc images and then run smoke test to make sure everything is good, however, it keeps on failing during the smoke test with the following error:

`RuntimeError: Verification of custom image dataproc-debian9-1-4-12-test failed: Unable to instantiate workflow template.`

Command that I'm running to build the image is:

```
python3 generate_custom_image.py --image-name dataproc-debian9-1-4-12-test \
  --customization-script ./scripts/debian9_image_prep.sh \
  --zone us-west2-a \
  --gcs-bucket gs://test-lab-fftest \
  --dataproc-version 1.4.12-debian9 \
  --project-id test-lab-fftest \
  --family dataproc-debian9
```

I'm using the latest `generate_custom_image.py` and startup scripts from [here](https://github.com/GoogleCloudDataproc/custom-images).

Bash version = `GNU bash, version 5.0.16(1)-release (x86_64-apple-darwin19.3.0)`
gcloud configuration = 
```
[compute]
region = us-west2
zone = us-west2-a
[core]
account = farahfa@company.com
disable_usage_reporting = True
project = test-lab-fftest
[dataproc]
region = us-west2
```

Trace log = 
```
INFO:custom_image_utils.smoke_test_runner:Successfully created Dataproc workflow-template verify-image-20200304122000-130d6d64 with image dataproc-debian9-1-4-12-test...
INFO:custom_image_utils.smoke_test_runner:Smoke testing Dataproc workflow-template %s...
Waiting on operation [projects/test-lab-fftest/regions/us-west2/operations/bd1746c2-71f4-3334-8246-6b5ef8d5f8fe].
WorkflowTemplate [verify-image-20200304122000-130d6d64] RUNNING
Creating cluster: Operation ID [projects/test-lab-fftest/regions/us-west2/operations/b8b555b1-020c-497e-b840-b44e4721d5f1].
Create cluster operation cancelled
Deleting cluster: Operation ID [projects/test-lab-fftest/regions/us-west2/operations/9c92c219-258b-3e04-860f-7774f61e56ed].
ERROR: (gcloud.beta.dataproc.workflow-templates.instantiate) Operation [projects/test-lab-fftest/regions/us-west2/operations/bd1746c2-71f4-3334-8246-6b5ef8d5f8fe] timed out.
ERROR:custom_image_utils.smoke_test_runner:Verification of custom image dataproc-debian9-1-4-12-test failed: Unable to instantiate workflow template.
INFO:custom_image_utils.smoke_test_runner:Deleting Dataproc workflow-template verify-image-20200304122000-130d6d64...
INFO:custom_image_utils.smoke_test_runner:Successfully deleted Dataproc workflow-template verify-image-20200304122000-130d6d64...
Traceback (most recent call last):
  File "/Users/farahfa/workdir/projects/dataproc-images/custom_image_utils/smoke_test_runner.py", line 111, in _verify_custom_image
    _instantiate_workflow_template(workflow_name, project_id)
  File "/Users/farahfa/workdir/projects/dataproc-images/custom_image_utils/smoke_test_runner.py", line 80, in _instantiate_workflow_template
    raise RuntimeError("Unable to instantiate workflow template.")
RuntimeError: Unable to instantiate workflow template.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_custom_image.py", line 95, in <module>
    main()
  File "generate_custom_image.py", line 90, in main
    smoke_test_runner.run(args)
  File "/Users/farahfa/workdir/projects/dataproc-images/custom_image_utils/smoke_test_runner.py", line 136, in run
    args.network, args.subnetwork)
  File "/Users/farahfa/workdir/projects/dataproc-images/custom_image_utils/smoke_test_runner.py", line 118, in _verify_custom_image
    raise RuntimeError(err_msg)
RuntimeError: Verification of custom image dataproc-debian9-1-4-12-test failed: Unable to instantiate workflow template.
```

Workflow template = 
```
createTime: '2020-03-04T20:20:02.511Z'
id: verify-image-20200304122000-130d6d64
jobs:
- sparkJob:
    args:
    - '1000'
    jarFileUris:
    - file:///usr/lib/spark/examples/jars/spark-examples.jar
    mainClass: org.apache.spark.examples.SparkPi
  stepId: '001'
name: projects/test-lab-fftest/regions/us-west2/workflowTemplates/verify-image-20200304122000-130d6d64
placement:
  managedCluster:
    clusterName: verify-image-20200304122000-130d6d64
    config:
      gceClusterConfig:
        networkUri: https://compute.googleapis.com/compute/beta/projects/test-lab-fftest/global/networks/default
        zoneUri: us-west2-a
      masterConfig:
        imageUri: https://compute.googleapis.com/compute/beta/projects/test-lab-fftest/global/images/dataproc-debian9-1-4-12-test
      workerConfig:
        imageUri: https://compute.googleapis.com/compute/beta/projects/test-lab-fftest/global/images/dataproc-debian9-1-4-12-test
updateTime: '2020-03-04T20:20:05.497Z'
version: 3
```

Any idea why this is happening and how to fix it?

**Comment by farahfa** [comment]
Nevermind, our automated safeguards were automatically flagging the cluster as non-compliant and cancelling the operation. Please ignore this.

**Comment by MattConflitti** [comment]
@farahfa Do you mind expanding on what the fix was for this? We are experiencing the same issue. Thanks!
