### ISSUE TITLE
Spark 3.0 Horovod training Fails with HDSF error

### ISSUE THREAD

**Issue by arunraman** [GoogleCloudDataproc/cloud-dataproc#138]
I have a dataproc cluster with the following image.

Image : 2.0.0-RC1-ubuntu18

I modified an example from the Horovod Spark

https://github.com/horovod/horovod/blob/master/examples/keras_spark_rossmann_estimator.py

I am hitting the following error on this line 

`    keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])
`

`hdfsExists: invokeMethod((Lorg/apache/hadoop/fs/Path;)Z) error:
ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Messagejava.lang.ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Message
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
	at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:907)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1666)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1573)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1588)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
Traceback (most recent call last):
  File "/tmp/537ae15236734a5c8b9e60faac43c629/sparkjob1.py", line 335, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 37, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 129, in fit
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 78, in _fit
    verbose=self.getVerbose()) as dataset_idx:
  File "/opt/conda/default/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/util.py", line 636, in prepare_data
    num_partitions, num_processes, verbose)
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/util.py", line 572, in _get_or_create_dataset
    store, label_columns, feature_columns, sample_weight_col, dataset_idx)
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/util.py", line 413, in get_simple_meta_from_parquet
    raise ValueError("{} path does not exist in the store".format(train_data_path))
ValueError: hdfs:///tmp/horovod/intermediate_train_data.0 path does not exist in the store`

Even though I can see the files available in the hdfs.

`hadoop  fs -ls /tmp/horovod/intermediate_
/tmp/horovod/intermediate_train_data.0  /tmp/horovod/intermediate_val_data.0    
arraman@nvsparkgpu-m:~$ hadoop  fs -ls /tmp/horovod/intermediate_train_data.0 ra
Found 17 items
-rw-r--r--   2 root hadoop          0 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/_SUCCESS
-rw-r--r--   2 root hadoop    1027422 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00000-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1021719 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00001-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1025107 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00002-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1019034 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00003-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1024424 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00004-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1021981 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00005-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1023346 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00006-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1021876 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00007-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1024823 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00008-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1026777 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00009-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1033677 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00010-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1034280 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00011-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1026418 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00012-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1026736 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00013-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1033822 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00014-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1025689 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00015-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet`

The raw data is coming from the GCS.

**Comment by medb** [comment]
What flags do you set to run Horovod example? Specifically, what do you set `--data-dir` and `--work-dir` flags too?

**Comment by arunraman** [comment]
For the data-dir i am using a gs://bucket/dataand for --work-dir I tried using a gs://bucket/result that didn't work, so I hardcoded a hdfs location.

**Comment by medb** [comment]
How do you install Horovod on Dataproc cluster?

**Comment by roarjn** [comment]
We did `apt-get install openmpi-bin`,  `pip install --user tensorflow==1.15`, and `HOROVOD_GPU_OPERATIONS=NCCL pip install --user horovod[spark]` on master and worker nodes.

**Comment by medb** [comment]
Stack trace shows that Horovod fails when it tries to read from HDFS:
```
. . .
  at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1666)
. . .
```

This should not happen if you specified GCS for a data and work dirs. Does it happen because you somehow modified `keras_spark_rossmann_estimator.py`? Is not modified `keras_spark_rossmann_estimator.py` example fails too?

Generally speaking this stack trace seems to indicate that there are binary incompatibility between multiple Java Protobuf libraries. Hadoop and Spark on Dataproc use Protobuf 2.5.0. Did you modify in any way Spark and/or Hadoop installation on Dataproc cluster to include newer version of Protobuf?

**Comment by arunraman** [comment]
No we have not modified the Hadoop in the dataproc in any way.

`gcloud beta dataproc clusters create $CLUSTER_NAME  \
    --zone $ZONE \
    --region $REGION \
    --image-version=2.0.0-RC1-ubuntu18 \
    --master-machine-type n1-standard-8 \
    --master-boot-disk-size 500 \
    --num-workers $NUM_WORKERS \
    --worker-accelerator type=nvidia-tesla-t4,count=$NUM_GPUS \
    --worker-machine-type n1-highmem-16 \
    --worker-boot-disk-size 500 \
    --initialization-actions gs://$GCS_BUCKET/install_gpu_driver.sh \
    --optional-components=ANACONDA,JUPYTER,ZEPPELIN \
    --metadata gpu-driver-provider="NVIDIA" \
    --metadata rapids-runtime="SPARK" \
    --metadata cuda-version="10.1" \
    --metadata install-gpu-agent=true \
    --bucket $GCS_BUCKET \
    --subnet=default \
    --enable-component-gateway \
    --properties "^#^spark:spark.dynamicAllocation.enabled=false#spark:spark.shuffle.service.enabled=false#capacity-scheduler:yarn.scheduler.capacity.resource-calculator=org.apache.hadoop.yarn.util.resource.DominantResourceCalculator#yarn:yarn.resource-types=yarn.io/gpu#yarn:yarn.nodemanager.resource-plugins=yarn.io/gpu#yarn:yarn.nodemanager.resource-plugins.gpu.allowed-gpu-devices=auto#yarn:yarn.nodemanager.resource-plugins.gpu.path-to-discovery-executables=/usr/bin#yarn:yarn.nodemanager.linux-container-executor.cgroups.mount=true#yarn:yarn.nodemanager.linux-container-executor.cgroups.mount-path=/sys/fs/cgroup#yarn:yarn.nodemanager.linux-container-executor.cgroups.hierarchy=yarn#yarn:yarn.nodemanager.container-executor.class=org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor#yarn:yarn.nodemanager.linux-container-executor.group=yarn#spark:spark.rapids.sql.concurrentGpuTasks=2#spark:spark.rapids.memory.pinnedPool.size=8G#spark:spark.executor.memoryOverhead=8G#spark:spark.executor.extraJavaOptions='-Dai.rapids.cudf.prefer-pinned=true'#spark:spark.locality.wait=0s#spark:spark.sql.files.maxPartitionBytes=512m#spark:spark.executor.resource.gpu.discoveryScript=/usr/lib/spark/scripts/gpu/getGpusResources.sh#spark:spark.sql.shuffle.partitions=16#spark:spark.task.cpus=1#spark:spark.executor.resource.gpu.amount=1#spark:spark.task.resource.gpu.amount=0.125"`

This is the cluster creation command and the init script is here.

https://raw.githubusercontent.com/mengdong/initialization-actions/patch-1/gpu/install_gpu_driver.sh

**Comment by medb** [comment]
Judging from [this](https://groups.google.com/forum/#!topic/janusgraph-users/_EnKw6W-Zio) and [this](https://github.com/horovod/horovod/issues/588) threads it seems that issue is that Horovod can not find HDFS jar on classpath, to fix it you should add `-x CLASSPATH="$(hadoop classpath --glob)"` to your Horovod command (see previously linked thread).
